workflows:
  ios-build:
    name: iOS IPA Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean and get dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build unsigned IPA
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
      - build/ios/**/*.ipa
