workflows:
  build_ios_ipa:
    name: "Build iOS IPA (no signing)"
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign
          mkdir -p build/ios/ipa
          cd build/ios/iphoneos
          zip -r Runner.ipa Runner.app
          mv Runner.ipa ../ipa/
    artifacts:
      - build/ios/ipa/Runner.ipa
